
import json, time, hashlib, random
from typing import Tuple
from .provider_base import BaseProvider

class MockProvider(BaseProvider):
    def generate(self, system, user, model, temperature, max_tokens) -> Tuple[str, int, int, int]:
        t0 = time.time()
        seed = int(hashlib.sha256((system or "" + "|" + user).encode()).hexdigest(), 16) % (10**8)
        rnd = random.Random(seed)
        title = "Quick " + str(abs(seed) % 1000) + " Snack"
        servings = 2 + rnd.randint(0, 4)
        prep = 5 + rnd.randint(0, 15)
        cook = 5 + rnd.randint(0, 20)
        total = prep + cook
        ingredients = []
        for i in range(1, 6):
            ingredients.append({"name": f"Item {i}", "quantity": float(rnd.randint(1, 3)), "unit": "cup" if i % 2 == 0 else "tbsp", "notes": None, "icon": None})
        equipment = [{"name": "Bowl", "icon": None}, {"name": "Pan", "icon": None}]
        steps = []
        for i in range(1, 5):
            steps.append({"number": i, "instruction": f"Do step {i}", "equipment": ["Bowl"] if i < 3 else ["Pan"], "duration_min": rnd.randint(1, 10)})
        nutrition = {"calories": 300 + rnd.randint(0, 200), "protein_g": float(10 + rnd.randint(0, 10)), "fat_g": float(10 + rnd.randint(0, 10)), "carbs_g": float(20 + rnd.randint(0, 20))}
        tags = ["test", "mock"]
        source = {"author": None, "url": None}
        description = "Generated by mock provider"
        recipe = {
            "title": title,
            "description": description,
            "servings": servings,
            "time": {"prep_min": prep, "cook_min": cook, "total_min": total},
            "ingredients": ingredients,
            "equipment": equipment,
            "steps": steps,
            "nutrition": nutrition,
            "tags": tags,
            "source": source,
            "version": 1
        }
        text = json.dumps(recipe, ensure_ascii=False)
        dur = int((time.time() - t0) * 1000)
        return text, dur, 200, len(text)
